import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "duchess-house",
    name: "Duchess House",
    label: "2022",
    year: 2022,
    location: "West Vancouver",
    sqft: "3,056 ft²",
    thumb: "/images/projects/duchess-house/01.jpg",
    thumbAlt: "Duchess House — twilight front elevation",
    placement: { colStart: 1, colSpan: 7, rowOffset: 0 },
    hasDetail: true,
    description: [
      "Duchess House is a testament to intelligent design and precision craftsmanship. Built on a compact lot with challenging setbacks, this custom home maximizes every square foot through thoughtful planning, seamless indoor-outdoor living, and refined contemporary architecture. The result is a residence that feels remarkably spacious, blending clean modern design, premium finishes, and exceptional functionality into a home that proves luxury is defined by design—not size.",
    ],
    detailImages: [
      { src: "/images/projects/duchess-house/01.jpg", alt: "Duchess House — twilight front elevation" },
      { src: "/images/projects/duchess-house/02.jpg", alt: "Duchess House — garage and driveway at dusk" },
      { src: "/images/projects/duchess-house/03.jpg", alt: "Duchess House — aerial view toward Lions Gate Bridge" },
      { src: "/images/projects/duchess-house/04.jpg", alt: "Duchess House — daytime aerial with mountain backdrop" },
      { src: "/images/projects/duchess-house/05.jpg", alt: "Duchess House — twilight view of house and garage" },
      { src: "/images/projects/duchess-house/06.jpg", alt: "Duchess House — rooftop deck at dusk" },
      { src: "/images/projects/duchess-house/07.jpg", alt: "Duchess House — rooftop deck lounge, overhead view" },
      { src: "/images/projects/duchess-house/08.jpg", alt: "Duchess House — front facade in daylight" },
    ],
  },
  {
    slug: "inglewood-house",
    name: "Inglewood House",
    label: "2019",
    year: 2019,
    location: "West Vancouver",
    sqft: "6,150 ft²",
    thumb: "/images/projects/inglewood-house/01.jpeg",
    thumbAlt: "Inglewood House — twilight front exterior",
    placement: { colStart: 8, colSpan: 5, rowOffset: 5 },
    hasDetail: true,
    description: [
      "Inglewood House is a modern custom home that demonstrates the balance between architecture, functionality, and craftsmanship. The primary design challenge was creating a private backyard while preserving sunlight in a dense residential setting. This was achieved through strategic building placement, expansive glazing, and carefully considered outdoor spaces. A soaring double-height dining area serves as the home's centerpiece, creating a strong visual connection between both floors and enhancing the sense of openness throughout.",
    ],
    detailImages: [
      { src: "/images/projects/inglewood-house/01.jpeg", alt: "Inglewood House — twilight front exterior" },
      { src: "/images/projects/inglewood-house/02.jpeg", alt: "Inglewood House — double-height dining area and floating stair" },
      { src: "/images/projects/inglewood-house/03.jpeg", alt: "Inglewood House — entry foyer" },
      { src: "/images/projects/inglewood-house/04.jpeg", alt: "Inglewood House — living room at twilight" },
      { src: "/images/projects/inglewood-house/05.jpeg", alt: "Inglewood House — rear patio opening to living area" },
      { src: "/images/projects/inglewood-house/06.jpeg", alt: "Inglewood House — front entry and water feature at twilight" },
      { src: "/images/projects/inglewood-house/07.jpeg", alt: "Inglewood House — kitchen island" },
      { src: "/images/projects/inglewood-house/08.jpeg", alt: "Inglewood House — upper landing and glass bridge" },
      { src: "/images/projects/inglewood-house/09.jpeg", alt: "Inglewood House — primary ensuite bath" },
      { src: "/images/projects/inglewood-house/10.jpeg", alt: "Inglewood House — lounge and wine display" },
      { src: "/images/projects/inglewood-house/11.jpeg", alt: "Inglewood House — sauna and shower" },
      { src: "/images/projects/inglewood-house/12.jpeg", alt: "Inglewood House — home theatre" },
      { src: "/images/projects/inglewood-house/13.jpeg", alt: "Inglewood House — covered patio with firepit" },
      { src: "/images/projects/inglewood-house/14.jpeg", alt: "Inglewood House — garage exterior at twilight" },
    ],
  },
  {
    slug: "nelson-house",
    name: "Nelson House",
    label: "2016",
    year: 2016,
    location: "West Vancouver",
    sqft: "4,325 ft²",
    thumb: "/images/projects/nelson-house/01.jpeg",
    thumbAlt: "Nelson House — front exterior",
    placement: { colStart: 3, colSpan: 7, rowOffset: 18 },
    hasDetail: true,
    description: [
      "This custom contemporary residence marked the beginning of Primal Construction's journey. Designed to embrace its elevated setting, the home was carefully positioned to maximize ocean views while creating seamless connections between indoor and outdoor living.",
      "Featuring expansive covered terraces, a chef's kitchen, temperature-controlled wine display, home theatre, and refined custom millwork throughout, the project showcases the quality, precision, and thoughtful design principles that have become the foundation of every home we build.",
    ],
    detailImages: [
      { src: "/images/projects/nelson-house/01.jpeg", alt: "Nelson House — front exterior" },
      { src: "/images/projects/nelson-house/02.jpeg", alt: "Nelson House — covered terrace with ocean view" },
      { src: "/images/projects/nelson-house/03.jpeg", alt: "Nelson House — living room with ocean view and fireplace" },
      { src: "/images/projects/nelson-house/04.jpeg", alt: "Nelson House — open dining, kitchen, and living area" },
      { src: "/images/projects/nelson-house/05.jpeg", alt: "Nelson House — kitchen island with ocean-view windows" },
      { src: "/images/projects/nelson-house/06.jpeg", alt: "Nelson House — primary ensuite with freestanding tub" },
      { src: "/images/projects/nelson-house/07.jpeg", alt: "Nelson House — family room" },
      { src: "/images/projects/nelson-house/08.jpeg", alt: "Nelson House — wine display and wet bar" },
      { src: "/images/projects/nelson-house/09.jpeg", alt: "Nelson House — home theatre" },
    ],
  },
];

export const projectMap = Object.fromEntries(projects.map((p) => [p.slug, p]));
